"""add is_finish field into task model./

Revision ID: 11a0a9f02217
Revises: d05ce8440afb
Create Date: 2026-08-18 13:19:15.803428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11a0a9f02217'
down_revision: Union[str, Sequence[str], None] = 'd05ce8440afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_finish', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_finish')
    # ### end Alembic commands ###
